var ketikan = new Typed(".auto-input", {
    strings: [
        "Selamat Datang di",
        "Welcome to",
        "ようこそ",
        "Willkommen zu",
        "Bienvenue à",
        "Добро пожаловать в",
        "welkom bij",
        "에 오신 것을 환영합니다",
        "Välkommen till",
        "Bienvenido a",
        " ಸುಸ್ವಾಗತ",
        "Wilujeng sumping",
        " ยินดีต้อนรับสู่",
        "Hoşgeldiniz",
    ],
    typeSpeed: 140,
    backSpeed: 40,
    smartBackspace: true,
    shuffle: true,
    loop: true,
});
